import Wow284.DiagonalizationLeft
import Wow284.DiagonalizationDistance

/-!
This file is generated by `scripts/generate_lean_diagonalization.py`.
It exposes the exact rational diagonalization used by the WOW-284
formalization and checks its eigenvalue multiplicities.
-/

namespace Wow284

theorem distance_diagonal_counts :
    (Finset.univ.filter fun j : Vertex => distanceDiagonalEntry j = -4).card = 28 ∧
    (Finset.univ.filter fun j : Vertex => distanceDiagonalEntry j = 1).card = 21 ∧
    (Finset.univ.filter fun j : Vertex => distanceDiagonalEntry j = 91).card = 1 := by
  decide

end Wow284
