#!/usr/bin/env python3
"""Generate exact Lean matrix data for the 40-vertex counterexample.

The generated development deliberately mirrors the existing 50-vertex
`generate_lean_diagonalization.py`: integer matrices, denominator clearing,
5x5 certificate shards, and a rational diagonalization wrapper.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

import sympy as sp

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

from common_graphs import distance_matrix, graph40, primitive_integer_column  # noqa: E402

LEAN_DIR = ROOT / "lean" / "Wow284" / "Induced40"


def lean_rat(value: sp.Expr) -> str:
    value = sp.Rational(value)
    if value.q == 1:
        return str(int(value.p))
    return f"(({int(value.p)} : ℚ) / {int(value.q)})"


def lean_int_matrix(name: str, matrix: sp.Matrix) -> str:
    rows: list[str] = []
    for i in range(matrix.rows):
        entries: list[str] = []
        for j in range(matrix.cols):
            value = sp.Rational(matrix[i, j])
            if value.q != 1:
                raise AssertionError(f"{name}[{i},{j}] is not integral: {value}")
            entries.append(str(int(value)))
        rows.append(", ".join(entries))
    return f"def {name} : Matrix Vertex Vertex ℤ := !![\n    " + ";\n    ".join(rows) + "\n  ]\n"


def shard(name: str, lhs: str, rhs: str, r: int) -> str:
    lines: list[str] = []
    for s in range(8):
        lines += [
            "set_option maxRecDepth 10000 in",
            f"lemma {name}_rows_{r}_{s} : ∀ c d : Fin 5,",
            f"    ({lhs}) (coordVertex {r} c) (coordVertex {s} d) =",
            f"      ({rhs}) (coordVertex {r} c) (coordVertex {s} d) := by",
            "  decide",
            "",
        ]
    lines += [
        f"lemma {name}_row_{r} (s : Fin 8) (c d : Fin 5) :",
        f"    ({lhs}) (coordVertex {r} c) (coordVertex s d) =",
        f"      ({rhs}) (coordVertex {r} c) (coordVertex s d) := by",
        "  fin_cases s",
    ]
    lines += [f"  · exact {name}_rows_{r}_{s} c d" for s in range(8)]
    lines.append("")
    return "\n".join(lines)


def assembly(name: str, lhs: str, rhs: str) -> str:
    lines = [
        f"private lemma {name}_coord (r s : Fin 8) (c d : Fin 5) :",
        f"    ({lhs}) (coordVertex r c) (coordVertex s d) =",
        f"      ({rhs}) (coordVertex r c) (coordVertex s d) := by",
        "  fin_cases r",
    ]
    lines += [f"  · exact {name}_row_{r} s c d" for r in range(8)]
    lines += [
        "",
        f"theorem {name} : {lhs} = {rhs} := by",
        "  ext i j",
        "  rw [← coordVertex_surj i, ← coordVertex_surj j]",
        f"  exact {name}_coord _ _ _ _",
        "",
    ]
    return "\n".join(lines)


def render() -> dict[Path, str]:
    graph, _ = graph40()
    d = distance_matrix(graph)
    identity = sp.eye(40)

    columns: list[sp.Matrix] = [sp.ones(40, 1)]
    diagonal_entries = [75]
    for eigenvalue, multiplicity in [(-5, 18), (3, 5), (0, 16)]:
        nullspace = (d - eigenvalue * identity).nullspace()
        if len(nullspace) != multiplicity:
            raise AssertionError((eigenvalue, len(nullspace), multiplicity))
        columns.extend(primitive_integer_column(v) for v in nullspace)
        diagonal_entries.extend([eigenvalue] * multiplicity)

    basis = sp.Matrix.hstack(*columns)
    if basis.det() == 0:
        raise AssertionError("eigenbasis is singular")
    inverse = basis.inv()
    denominator = sp.ilcm(*[sp.denom(x) for x in inverse])
    inverse_numerator = inverse * denominator
    diagonal = sp.diag(*diagonal_entries)

    if denominator != 600:
        raise AssertionError(f"unexpected inverse denominator {denominator}")
    if not all(sp.denom(x) == 1 for x in inverse_numerator):
        raise AssertionError("scaled inverse is not integral")
    if d * basis != basis * diagonal:
        raise AssertionError("distance diagonalization failed")
    if inverse_numerator * basis != denominator * identity:
        raise AssertionError("scaled left inverse failed")

    definitions = f'''import Wow284.Induced40.Basic

/-!
Generated by `scripts/generate_lean40_diagonalization.py`.
The data are exact integer matrices; no floating-point value occurs here.
-/

namespace Wow284.Induced40

open Matrix

{lean_int_matrix("Dcert", d)}
{lean_int_matrix("eigenbasisInt", basis)}
{lean_int_matrix("eigenbasisInvNumerator", inverse_numerator)}
{lean_int_matrix("distanceDiagonalInt", diagonal)}

def castMatrix (M : Matrix Vertex Vertex ℤ) : Matrix Vertex Vertex ℚ :=
  M.map (Int.castRingHom ℚ)

lemma castMatrix_mul (M N : Matrix Vertex Vertex ℤ) :
    castMatrix (M * N) = castMatrix M * castMatrix N := by
  exact Matrix.map_mul

 def eigenbasis : Matrix Vertex Vertex ℚ := castMatrix eigenbasisInt
 def eigenbasisInv : Matrix Vertex Vertex ℚ :=
   ((1 : ℚ) / {denominator}) • castMatrix eigenbasisInvNumerator
 def Dq : Matrix Vertex Vertex ℚ := castMatrix Dcert
 def distanceDiagonal : Matrix Vertex Vertex ℚ := castMatrix distanceDiagonalInt
 def scaledIdentityInt : Matrix Vertex Vertex ℤ :=
   fun i j => if i = j then {denominator} else 0

end Wow284.Induced40
'''.replace("\n def ", "\ndef ")

    outputs: dict[Path, str] = {LEAN_DIR / "DiagonalizationDefinitions.lean": definitions}
    identities = [
        ("Left", "eigenbasis_left_inverse_scaled", "eigenbasisInvNumerator * eigenbasisInt", "scaledIdentityInt"),
        ("Distance", "distance_diagonalization_int", "Dcert * eigenbasisInt", "eigenbasisInt * distanceDiagonalInt"),
    ]
    for kind, name, lhs, rhs in identities:
        for r in range(8):
            outputs[LEAN_DIR / f"Diagonalization{kind}{r}.lean"] = f'''import Wow284.Induced40.DiagonalizationDefinitions

/-! Generated bounded 5x5 certificate shard. -/
namespace Wow284.Induced40

{shard(name, lhs, rhs, r)}
end Wow284.Induced40
'''
        imports = "\n".join(f"import Wow284.Induced40.Diagonalization{kind}{r}" for r in range(8))
        body = f'''{imports}

namespace Wow284.Induced40

open Matrix

{assembly(name, lhs, rhs)}
'''
        if kind == "Left":
            body += f'''theorem eigenbasis_left_inverse :
    eigenbasisInv * eigenbasis = (1 : Matrix Vertex Vertex ℚ) := by
  change (((1 : ℚ) / {denominator}) • castMatrix eigenbasisInvNumerator) *
    castMatrix eigenbasisInt = 1
  rw [Matrix.smul_mul, ← castMatrix_mul, eigenbasis_left_inverse_scaled]
  ext i j
  by_cases h : i = j
  · subst j
    simp [castMatrix, scaledIdentityInt]
  · simp [castMatrix, scaledIdentityInt, h]

theorem eigenbasis_right_inverse :
    eigenbasis * eigenbasisInv = (1 : Matrix Vertex Vertex ℚ) := by
  exact mul_eq_one_comm.mp eigenbasis_left_inverse

'''
        else:
            body += '''theorem distance_diagonalization :
    Dq * eigenbasis = eigenbasis * distanceDiagonal := by
  change castMatrix Dcert * castMatrix eigenbasisInt =
    castMatrix eigenbasisInt * castMatrix distanceDiagonalInt
  simpa only [← castMatrix_mul] using congrArg castMatrix distance_diagonalization_int

'''
        body += "end Wow284.Induced40\n"
        outputs[LEAN_DIR / f"Diagonalization{kind}.lean"] = body

    outputs[LEAN_DIR / "DiagonalizationData.lean"] = '''import Wow284.Induced40.DiagonalizationLeft
import Wow284.Induced40.DiagonalizationDistance

namespace Wow284.Induced40

/-- The generated diagonal contains the complete distance spectrum. -/
theorem distance_diagonal_counts :
    (Finset.univ.filter fun j : Vertex => distanceDiagonalInt j j = -5).card = 18 ∧
    (Finset.univ.filter fun j : Vertex => distanceDiagonalInt j j = 3).card = 5 ∧
    (Finset.univ.filter fun j : Vertex => distanceDiagonalInt j j = 0).card = 16 ∧
    (Finset.univ.filter fun j : Vertex => distanceDiagonalInt j j = 75).card = 1 := by
  decide

end Wow284.Induced40
'''
    return outputs


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs = render()
    if args.check:
        stale = [p for p, c in outputs.items() if not p.exists() or p.read_text(encoding="utf-8") != c]
        if stale:
            raise SystemExit("stale files: " + ", ".join(str(p.relative_to(ROOT)) for p in stale))
        print(f"40-vertex Lean data: PASS ({len(outputs)} files)")
        return
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
        print(path.relative_to(ROOT))


if __name__ == "__main__":
    main()
